[package]
name = "age-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.1.5"
lalrpop-util = { version = "0.19.8", features = ["lexer"] }
